version: '3'

services:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sml12345

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: sml12345
      ME_CONFIG_MONGODB_URL: mongodb://root:sml12345@mongo:27017/

  web:
    container_name: web
    build:
      context: ..
      dockerfile: build/Dockerfile
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
